### PRODUCTS INDEX
GET http://localhost:3000/products.json

POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "phone",
  "price": 1000,
  "description": "Makes calls"
}

### DELETE REQUEST

DELETE http://localhost:3000/products/19.json
# Content-Type: application/json

# {
#   "product_id": "id" 
# }

### UPDATE ACTION
PATCH http://localhost:3000/products/16.json
Content-Type: application/json

{
  "name": "Iphone",
  "price": 2000,
  "description": "Makes expensive calls"
}