### PRODUCTS INDEX
GET http://localhost:3000/products.json

###
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "pprroodduct",
  "price": 10,
  "description": "ahhhhhhh"
}

### DELETE REQUEST

DELETE http://localhost:3000/products/24.json



### UPDATE ACTION
PATCH http://localhost:3000/products/24.json
Content-Type: application/json

{
  "name": "Remote Iphone",
  "price": 52,
  "description": "calls things remotely"
}


### SUPPLIER REQUESTS
###INDEX
GET http://localhost:3000/suppliers.json
Content-Type: application/json

###SHOW
GET http://localhost:3000/suppliers/3.json
Content-Type: application/json

###CREATE
POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": "Nike",
  "email": "nike@email.com",
  "phone_number": "555-123-7891"
}

###UPDATE
PATCH http://localhost:3000/suppliers/3.json
Content-Type: application/json

{
  "name": "Adidas",
  "email": "adidas@email.com"
}

###DESTROY
DELETE  http://localhost:3000/suppliers/4.json
Content-Type: application/json