### PRODUCTS INDEX
GET http://localhost:3000/products.json

###
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "pprroodduct",
  "price": 10,
  "description": "ahhhhhhh"
}

### DELETE REQUEST

DELETE http://localhost:3000/products/24.json



### UPDATE ACTION
PATCH http://localhost:3000/products/24.json
Content-Type: application/json

{
  "name": "Remote Iphone",
  "price": 52,
  "description": "calls things remotely"
}